framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/_application/SymfonyBeyondCrud/Infrastructure/Translations'
        fallbacks:
            - en
        providers:
