version: '3'

volumes:
  mysql:

services:

  mysql:
    image: mysql:8.0.33
    container_name: sbc_mysql
    environment:
      - MYSQL_USER=sbc
      - MYSQL_PASSWORD=sbc
      - MYSQL_DATABASE=sbc
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_ONETIME_PASSWORD=0
    # left out ONLY_FULL_GROUP_BY below to enable hacky group-by functionality in SimpleReadModelDBALRepository
    # this is no problem since we have this on the real server as well.
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --max_allowed_packet=32505856000 --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  httpd:
    image: nginx:alpine
    container_name: sbc_web
    working_dir: /opt/app
    volumes:
      - .:/opt/app
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "8080:8080"
    depends_on:
      - php

  php:
    image: wodby/php:8.3
    working_dir: /opt/app
    container_name: sbc_php
    depends_on:
      - mysql
    environment:
      - PHP_IDE_CONFIG=serverName=locodio-with-compose
      - PHP_DATE_TIMEZONE=Europe/Brussels
      - COMPOSER_ALLOW_SUPERUSER=1
      # - DATABASE_URL=mysql://sbc:sbc@mysql:3306/sbc
      - PHP_FPM_USER=wodby
      - PHP_FPM_GROUP=wodby
    volumes:
      - .:/opt/app
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  node:
    image: node:20
    user: node
    container_name: sbc_node
    command: tail -f /dev/null # This keeps the container running in the background.
    ports:
      - "5173:5173"
    volumes:
      - ./:/opt/app:cached
    working_dir: /opt/app