name: Frontend Build QA and Test

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      ## —— Npm install ————————————————————————————————————————————————————————

      - name: Nodejs install
        uses: actions/setup-node@v4
        with:
              node-version: '21'
      - run: npm ci
